/*
 * This file was automatically generated by EvoSuite
 * Tue Sep 19 00:15:23 GMT 2023
 */

package evoMock;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import evoMock.EnvExample;
import java.io.FileNotFoundException;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class EnvExample_ESTest extends EnvExample_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SystemInUtil.addInputLine("");
      EnvExample envExample0 = new EnvExample();
      try { 
        envExample0.checkContent();
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("\t\uFFFD\u0000B");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "2/14/14");
      SystemInUtil.addInputLine("\t\uFFFD\u0000B");
      EnvExample envExample0 = new EnvExample();
      boolean boolean0 = envExample0.checkContent();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SystemInUtil.addInputLine("FlsAHcJx\"mQrs");
      EnvExample envExample0 = new EnvExample();
      boolean boolean0 = envExample0.checkContent();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("\t\uFFFD\u0000B");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "1/14/14");
      SystemInUtil.addInputLine("\t\uFFFD\u0000B");
      EnvExample envExample0 = new EnvExample();
      boolean boolean0 = envExample0.checkContent();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      EnvExample envExample0 = new EnvExample();
      try { 
        envExample0.checkContent();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }
}
