/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 15 03:35:02 GMT 2023
 */

package evosuite.set;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import evosuite.set.Set;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class Set_Failed_ESTest extends Set_Failed_ESTest_scaffolding {

  // Contract violation: Undeclared exception check

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Set set0 = new Set();
      // Throws undeclared exception: null
      set0.add((Integer) null);
  }

  // Contract violation: Undeclared exception check
  // Contract violation: Undeclared exception (JCrasher style)

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      linkedList0.add((Integer) null);
      // Throws undeclared exception: null
      Set set0 = new Set(linkedList0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      linkedList0.add((Integer) null);
      // Throws undeclared exception (JCrasher heuristic): null
      Set set0 = new Set(linkedList0);
  }

  // Contract violation: Undeclared exception check

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Set set0 = new Set(linkedList0);
      Set set1 = new Set(linkedList0);
      Set set2 = set0.intersect(set1);
      Set set3 = set2.intersect(set1);
      // Throws undeclared exception: null
      set3.belongs((Integer) null);
  }

  // Contract violation: Undeclared exception check

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Set set0 = new Set(linkedList0);
      // Throws undeclared exception: null
      set0.intersect((Set) null);
  }

  // Contract violation: Undeclared exception check

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Set set0 = new Set();
      // Throws undeclared exception: null
      set0.remove((Integer) null);
  }

  // Contract violation: Undeclared exception check

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Set set0 = new Set();
      // Throws undeclared exception: null
      set0.union((Set) null);
  }
}
